### ISSUE TITLE
Commas missing in setup.py

### ISSUE THREAD

**Issue by iharsuvorau** [AutomatedProcessImprovement/extraneous-activity-delays#1]
Installing from the repository's root directory gives an error:

```
pip install -e .
Obtaining extraneous-activity-delays
  Preparing metadata (setup.py) ... done
ERROR: Could not find a version that satisfies the requirement pandassetuptoolslxmlnumpyscipyhyperoptlog_similarity_metrics (from extraneous-activity-delays) (from versions: none)
ERROR: No matching distribution found for pandassetuptoolslxmlnumpyscipyhyperoptlog_similarity_metrics
```

In `setup.py` https://github.com/AutomatedProcessImprovement/extraneous-activity-delays/blob/main/setup.py, commas are missing in `install_requires` to separate each package, so everything is read as one giant string.

**Comment by david-chapela** [comment]
@iharsuvorau, It should be solved with latest commit!
