### ISSUE TITLE
Is the latest log-similarity-metrics package compatible with the recent extraneous-activity-delays?

### ISSUE THREAD

**Issue by iharsuvorau** [AutomatedProcessImprovement/extraneous-activity-delays#2]
Importing packages doesn't work if we use the latest `log_similarity_metrics` which I do for the most recent metrics' implementations, this line 
https://github.com/AutomatedProcessImprovement/extraneous-activity-delays/blob/main/src/extraneous_activity_delays/enhance_with_delays.py#L17:

```
../external_tools/extraneous-activity-delays/src/extraneous_activity_delays/enhance_with_delays.py:17: in <module>
    from log_similarity_metrics.cycle_time_emd import cycle_time_emd
E   ModuleNotFoundError: No module named 'log_similarity_metrics.cycle_time_emd'
```

**Comment by david-chapela** [comment]
I updated the log-similarity-metrics dependency, it was using a quite old version with different submodule structure, should be ok now
