### ISSUE TITLE
Optimize the extraneous delays with AbsoluteEMD instead of CycleTimeEMD

### ISSUE THREAD

**Issue by iharsuvorau** [AutomatedProcessImprovement/extraneous-activity-delays#5]
This is another attempt to improve Simod's results using extraneous-activity-delays for timers discovery.

**Comment by david-chapela** [comment]
Closed with [commit 7b95991da69f40e3e753623815995b1c5bdb9c1e](https://github.com/AutomatedProcessImprovement/extraneous-activity-delays/commit/7b95991da69f40e3e753623815995b1c5bdb9c1e).

(@iharsuvorau) Added a parameter in the configuration to specify the optimization metric (Absolute timestamps EMD, Circadian timestamps EMD, or Cycle time EMD).
